from __future__ import annotations

from contextlib import AbstractContextManager
from dataclasses import dataclass
from typing import Protocol
from uuid import UUID

from pybank.domain.models import Account, Card, LedgerEntry


@dataclass(frozen=True)
class UserCredential:
    id: UUID
    full_name: str
    email: str
    password_hash: str
    password_salt: str


class UserRepository(Protocol):
    def find_by_email(self, email: str) -> UserCredential | None: ...
    def create(self, full_name: str, email: str, password_hash: str, password_salt: str) -> UserCredential: ...


class BankRepository(Protocol):
    def atomic(self) -> AbstractContextManager[None]: ...
    def next_iban_sequence(self) -> int: ...
    def add_account(self, account: Account) -> None: ...
    def get_account(self, account_id: UUID) -> Account | None: ...
    def get_account_by_iban(self, iban: str) -> Account | None: ...
    def list_accounts(self, customer_id: UUID) -> list[Account]: ...
    def update_account(self, account: Account) -> None: ...
    def add_ledger_entry(self, entry: LedgerEntry) -> None: ...
    def list_ledger_entries(self, account_id: UUID, limit: int = 100) -> list[LedgerEntry]: ...
    def add_card(self, card: Card) -> None: ...
    def get_card(self, card_id: UUID) -> Card | None: ...
    def list_cards(self, customer_id: UUID) -> list[Card]: ...
    def update_card(self, card: Card) -> None: ...
